sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  aliyun:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      bucket-name: springboot-demo76
      region: cn-beijing

  wechat:
    appid: wx8c8880d990726878
    secret: f93189b713fdc47995f6ec3d7730649c

  shop:
    address: 北京市海淀区上地十街10号

  baidu:
    ak: 6Q8EOa2FRe5I3OopEl5KwkspVhegHfO7

